[WIP] ELK for 19.10
open-io/ansible-role-openio-elasticsearch pull request #6
Opened 2019-12-14 06:02 UTC by fatpat

2019-12-19 22:04 UTC, cdelgehier requested changes

2019-12-19 22:04 UTC, cdelgehier commented on README.md
> +| openio_elasticsearch_pid_dir              | string  | Path to ES pid directory                |
no,  you can't change the wording
All oio roles defined `*pid_directory`

Please stay consistent

2019-12-19 22:04 UTC, cdelgehier commented on defaults/main.yml
> +openio_elasticsearch_sysconfig_dir: "/etc/oio/sds/{{ openio_elasticsearch_namespace }}/{{ openio_elasticsearch_servicename }}"
please stay consistent with other roles
Define it in `vars` instead of `default`

2019-12-19 22:04 UTC, cdelgehier commented on defaults/main.yml
> +openio_elasticsearch_bind_interface: "{{ openio_bind_mgmt_interface | d(ansible_default_ipv4.alias) }}"
either you choose openio_bind_mgmt_interface for the 3 roles, or openio_bind_interface but not a mix of both

2019-12-19 22:04 UTC, cdelgehier commented on defaults/main.yml
> -openio_elasticsearch_transport_tcp_port: 6450
no transport port ?

2019-12-19 22:04 UTC, cdelgehier commented on tasks/main.yml
>    tags: install
configure

2019-12-19 22:04 UTC, cdelgehier commented on tasks/main.yml
>      delay: 10
prefer `retry` instead of `delay`

2019-12-20 16:12 UTC, fatpat commented on README.md
> +| openio_elasticsearch_pid_dir              | string  | Path to ES pid directory                |
fixed

2020-01-18 08:40 UTC, fatpat commented on defaults/main.yml
> +openio_elasticsearch_sysconfig_dir: "/etc/oio/sds/{{ openio_elasticsearch_namespace }}/{{ openio_elasticsearch_servicename }}"
fixed

2020-01-18 08:40 UTC, fatpat commented on defaults/main.yml
> -openio_elasticsearch_transport_tcp_port: 6450
fixed

2020-01-18 08:40 UTC, fatpat commented on tasks/main.yml
>      delay: 10
fixed

2020-01-18 08:40 UTC, fatpat reviewed
seess OK to me

2020-01-18 08:41 UTC, fatpat commented on tasks/main.yml
>    tags: install
fixed

2020-01-18 08:41 UTC, fatpat commented on defaults/main.yml
> +openio_elasticsearch_bind_interface: "{{ openio_bind_mgmt_interface | d(ansible_default_ipv4.alias) }}"
fixed

2020-02-04 07:51 UTC, merged